#!/bin/env php
<?php

set_include_path(
    get_include_path()
    . PATH_SEPARATOR . './phplib' 
);

require_once 'Autoload.php';

function main() {
    $options = Util_OptionsParser::getOptions();

    $user = Util_EtsyUtil::getUser();
    $location = Util_EtsyUtil::getRepoLocation($user);

    $preChecks = array(
        new Precheck_ScriptRunner($location . '/bin/check_file_size'),
        new Precheck_CopyAge()
    );

    $cmdRunner = new CommandRunner($options['verbose']);

    $repoManager = new RepoManager_Git($location, $cmdRunner);
    $repoManager->runPrechecks($preChecks);

    # Generate diff if required
    $patch = $options['patch'];
    if (is_null($patch)) {
        $patch = $repoManager->generateDiff($options['staged-only']);
    }

    if ($options['dry-run']) {
        print "Not sending job to Jenkins (-n) diff is here: $patch\n";
        exit(0);
    }

    # Send to jenkins
    $jenkinsRunner = new JenkinsRunner(
        $cmdRunner,
        $repoManager->getRemotebranch("master"),
        $patch,
        $user
    );


    $jenkinsRunner->startJenkinsJob($options['jobs']);

    $callback = $options['callback'];
    if ($options['poll_for_completion'] || !is_null($callback)) {
        $jenkinsRunner->pollForCompletion($options['pretty']);
        $jenkinsRunner->executeCallback($callback);
    }
}

main();
