#!/bin/env php
<?php

set_include_path(
    get_include_path()
    . PATH_SEPARATOR . './phplib' 
);

require_once 'Autoload.php';

function main() {
    $options = Util_OptionsParser::getOptions();

    $user = Util_EtsyUtil::getUser();
    $repoPath = Util_EtsyUtil::getRepoPath($user);

    $preChecks = array(
        new Precheck_ScriptRunner($repoPath . '/bin/check_file_size'),
        new Precheck_CopyAge()
    );

    $cmdRunner = new CommandRunner($options['verbose']);

    $repoManager = new RepoManager_Git($repoPath, $cmdRunner);
    $repoManager->runPrechecks($preChecks);

    # Generate diff if required
    $patch = $options['patch'];
    if (is_null($patch)) {
        $patch = $repoManager->generateDiff($options['staged-only']);
    }

    if ($options['dry-run']) {
        print 'Not sending job to Jenkins (-n) diff is here:' . $patch . PHP_EOL;
        exit(0);
    }

    # Send to jenkins
    $jenkinsRunner = new JenkinsRunner(
        'cimaster-dev2.vm.ny4dev.etsy.com:8080',
        '/usr/etsy/jenkins-cli.jar',
        'try',
        $cmdRunner,
        $patch
    );

    $jenkinsRunner->setbranch($repoManager->getRemotebranch("master"));

    $jenkinsRunner->setSshKey('/home' . $user . '/.ssh/try_id_rsa');

    $jenkinsRunner->setUid($user . time());

    $jenkinsRunner->setSubJobs($options['jobs']);

    $jenkinsRunner->addCallback($options['callback']);

    $jenkinsRunner->startJenkinsJob($patch, $options['poll_for_completion']);
}

main();
