#!/usr/bin/env php
<?php

require_once __DIR__.'/vendor/autoload.php';

/**
 * A sample Try script that demonstrates using a TryRunner instance to run your job.
 */

$options_tuple = TryLib\TryRunner\Options::parse(
    $argv,
    "http://localhost:8080",  # URL to your jenkins server (without http)
    "try",             # Jenkins job name
    "try",             # (Optional) Prefix of subjob names for your master project
    "."                # (Optional) Working copy path (path to your local git repository)
);

$try_runner = TryLib\TryRunner\Builder::masterProject()
    ->optionsTuple($options_tuple)
    ->jenkinsCliJarPath("/usr/etsy/jenkins-cli.jar")
    ->prechecks(array(
        new TryLib\Precheck\GitCopyBehind(array('master')),
        new TryLib\Precheck\GitReportUntracked(),
    ))
    ->build();

exit($try_runner->run());
