#!/usr/bin/php
<?php

require_once "TryLib/Util/php-options/options.php";
require_once "TryLib/Autoload.php";

$jenkins_server = 'try.etsycorp.com';
$jenkins_cli_jar = '/usr/etsy/jenkins-cli.jar';
$jenkins_master_job = 'try54';

$usage_spec = "
try [options...] [subjob] [subjob] ...
--
h,help              Show help
n,diff-only         Create diff, but do not send to Hudson
v,verbose           Verbose (show shell commands as they're run)
p,patch=            Path to patch file to use instead of generating a diff
b,branch=           Name of the remote branch to diff and try against
c,show-results      Show final try job results
P,show-progress     Print subtasks progressively as they complete
s,staged            Use staged changes only to generate the diff
C,callback=         Callback string to execute at the end of the try run.
                    Use \${status} and \${url} as placeholders for the try build status and url
                    Example: --callback 'echo \"**Try status : [\${status}](\${url})**\"'
";

$parser = new Options($usage_spec);
list($options, $flags, $extra) = $parser->parse($argv);

$subjobs = array_slice($extra, 1);

list($user, $repo_path) = TryLib_Util_EtsyUtil::getUserAndRepoPath();

$cli = new TryLib_Cli($jenkins_server, $jenkins_cli_jar, $jenkins_master_job);
$cli->setOptions($options);
$cli->setSubJobs($subjobs);
$cli->setUserAndRepoPath($user, $repo_path);
$cli->run();

